// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbjdvzeilfcdrvtrekhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiamR2emVpbGZjZHJ2dHJla2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjYwNjksImV4cCI6MjA2MjcwMjA2OX0.4_fyG4HXJAxFp3QougQZDUT3r6E7VYsGlXkgNq1Q-eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);